custom.ssl: false
spring:
  kafka:
    consumer:
      bootstrap-servers: localhost:9093
      group-id: group_id
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      security.protocol: SSL
      ssl:
        protocol: TLSv1.2
        key-store-location: classpath:kafka.client.keystore.jks
        key-store-type: jks
        key-store-password: 123456
        key-password: 123456
        trust-store-location: classpath:kafka.client.truststore.jks
        trust-store-type: jks
        trust-store-password: 123456
    producer:
      bootstrap-servers: localhost:9093
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      security.protocol: SSL
      ssl:
        protocol: TLSv1.2
        key-store-location: classpath:kafka.client.keystore.jks
        key-store-type: jks
        key-store-password: 123456
        key-password: 123456
        trust-store-location: classpath:kafka.client.truststore.jks
        trust-store-type: jks
        trust-store-password: 123456
    properties:
      #Server host name verification is disabled by setting ssl.endpoint.identification.algorithm to an empty string
      ssl.endpoint.identification.algorithm: