custom.ssl: false
spring:
  kafka:
    consumer:
      bootstrap-servers: localhost:9093
      group-id: my.group.id
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      security.protocol: SSL
      ssl:
        key-store-type: PEM
        key-store-location: <pem file with private key, certificate and certificate chain>
        key-password: <private key password>
        trust-store-location: <pem file with certificate chain>
        trust-store-type: PEM
    producer:
      bootstrap-servers: localhost:9093
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      security.protocol: SSL
      ssl:
        key-store-type: PEM
        key-store-location: <pem file with private key, certificate and certificate chain>
        key-password:
        trust-store-location: <pem file with certificate chain>
    properties:
      #Server host name verification is disabled by setting ssl.endpoint.identification.algorithm to an empty string
      ssl.endpoint.identification.algorithm: